### ISSUE TITLE
Feature Request: Adopt GitHub Releases pattern

### ISSUE THREAD

**Issue by josdotso** [RavuAlHemio/prometheus_aci_exporter#2]
Hello again.  ref: #1 

Would you be willing to tag [Semantically-versioned](https://semver.org/) [GitHub Releases](https://help.github.com/en/articles/creating-releases) for this project in GitHub? If properly configured at DockerHub, this would allow version-pinned docker image tags to used by your users.

e.g. `docker pull ravualhemio/prometheus_aci_exporter:0.1.0`

Thanks,
Joshua

**Comment by RavuAlHemio** [comment]
Hi Joshua, I have modified the DockerHub configuration to automatically build tagged releases too. I hope that it works; I foolishly pushed v0.1.0 before changing the config.

**Comment by josdotso** [comment]
Excellent. Thanks so much!

**Comment by RavuAlHemio** [comment]
Seems to be working; the build of v0.1.1 was triggered automatically. Cheers!
